# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import xtquant_pb2 as xtquant__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xtquant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """====================== Service Definitions ======================

    Market data service — wraps xtquant.xtdata
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMarketData = channel.unary_unary(
                '/xtquant.MarketDataService/GetMarketData',
                request_serializer=xtquant__pb2.GetMarketDataRequest.SerializeToString,
                response_deserializer=xtquant__pb2.GetMarketDataResponse.FromString,
                _registered_method=True)
        self.GetFullTick = channel.unary_unary(
                '/xtquant.MarketDataService/GetFullTick',
                request_serializer=xtquant__pb2.GetFullTickRequest.SerializeToString,
                response_deserializer=xtquant__pb2.GetFullTickResponse.FromString,
                _registered_method=True)
        self.GetInstrumentDetail = channel.unary_unary(
                '/xtquant.MarketDataService/GetInstrumentDetail',
                request_serializer=xtquant__pb2.GetInstrumentDetailRequest.SerializeToString,
                response_deserializer=xtquant__pb2.InstrumentDetail.FromString,
                _registered_method=True)
        self.GetStockList = channel.unary_unary(
                '/xtquant.MarketDataService/GetStockList',
                request_serializer=xtquant__pb2.GetStockListRequest.SerializeToString,
                response_deserializer=xtquant__pb2.StockListResponse.FromString,
                _registered_method=True)
        self.GetSectorList = channel.unary_unary(
                '/xtquant.MarketDataService/GetSectorList',
                request_serializer=xtquant__pb2.Empty.SerializeToString,
                response_deserializer=xtquant__pb2.GetSectorListResponse.FromString,
                _registered_method=True)
        self.DownloadHistoryData = channel.unary_stream(
                '/xtquant.MarketDataService/DownloadHistoryData',
                request_serializer=xtquant__pb2.DownloadHistoryDataRequest.SerializeToString,
                response_deserializer=xtquant__pb2.DownloadProgress.FromString,
                _registered_method=True)
        self.GetTradingDates = channel.unary_unary(
                '/xtquant.MarketDataService/GetTradingDates',
                request_serializer=xtquant__pb2.GetTradingDatesRequest.SerializeToString,
                response_deserializer=xtquant__pb2.GetTradingDatesResponse.FromString,
                _registered_method=True)
        self.GetFinancialData = channel.unary_unary(
                '/xtquant.MarketDataService/GetFinancialData',
                request_serializer=xtquant__pb2.GetFinancialDataRequest.SerializeToString,
                response_deserializer=xtquant__pb2.GetFinancialDataResponse.FromString,
                _registered_method=True)
        self.DownloadFinancialData = channel.unary_stream(
                '/xtquant.MarketDataService/DownloadFinancialData',
                request_serializer=xtquant__pb2.DownloadFinancialDataRequest.SerializeToString,
                response_deserializer=xtquant__pb2.DownloadProgress.FromString,
                _registered_method=True)
        self.GetValuationMetrics = channel.unary_unary(
                '/xtquant.MarketDataService/GetValuationMetrics',
                request_serializer=xtquant__pb2.GetValuationMetricsRequest.SerializeToString,
                response_deserializer=xtquant__pb2.GetValuationMetricsResponse.FromString,
                _registered_method=True)
        self.SubscribeQuote = channel.unary_stream(
                '/xtquant.MarketDataService/SubscribeQuote',
                request_serializer=xtquant__pb2.SubscribeQuoteRequest.SerializeToString,
                response_deserializer=xtquant__pb2.QuoteUpdate.FromString,
                _registered_method=True)
        self.SubscribeWholeQuote = channel.unary_stream(
                '/xtquant.MarketDataService/SubscribeWholeQuote',
                request_serializer=xtquant__pb2.SubscribeWholeQuoteRequest.SerializeToString,
                response_deserializer=xtquant__pb2.TickSnapshot.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """====================== Service Definitions ======================

    Market data service — wraps xtquant.xtdata
    """

    def GetMarketData(self, request, context):
        """Get kline data -> xtdata.get_market_data_ex
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullTick(self, request, context):
        """Get real-time tick snapshot -> xtdata.get_full_tick
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstrumentDetail(self, request, context):
        """Get instrument detail -> xtdata.get_instrument_detail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockList(self, request, context):
        """Get sector constituents -> xtdata.get_stock_list_in_sector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSectorList(self, request, context):
        """Get sector list -> xtdata.get_sector_list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadHistoryData(self, request, context):
        """Download historical data (server stream) -> xtdata.download_history_data2
        Streams per-instrument progress; use for batch downloads with progress tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradingDates(self, request, context):
        """Get trading dates -> xtdata.get_trading_dates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinancialData(self, request, context):
        """Get financial data -> xtdata.get_financial_data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFinancialData(self, request, context):
        """Download financial data (server stream) -> xtdata.download_financial_data2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValuationMetrics(self, request, context):
        """Get valuation metrics (PE, PB computed from price/EPS/BPS; turnover, market cap, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeQuote(self, request, context):
        """Subscribe to single-stock quotes (server stream) -> xtdata.subscribe_quote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeWholeQuote(self, request, context):
        """Subscribe to full-market quotes (server stream) -> xtdata.subscribe_whole_quote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketData,
                    request_deserializer=xtquant__pb2.GetMarketDataRequest.FromString,
                    response_serializer=xtquant__pb2.GetMarketDataResponse.SerializeToString,
            ),
            'GetFullTick': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullTick,
                    request_deserializer=xtquant__pb2.GetFullTickRequest.FromString,
                    response_serializer=xtquant__pb2.GetFullTickResponse.SerializeToString,
            ),
            'GetInstrumentDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstrumentDetail,
                    request_deserializer=xtquant__pb2.GetInstrumentDetailRequest.FromString,
                    response_serializer=xtquant__pb2.InstrumentDetail.SerializeToString,
            ),
            'GetStockList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockList,
                    request_deserializer=xtquant__pb2.GetStockListRequest.FromString,
                    response_serializer=xtquant__pb2.StockListResponse.SerializeToString,
            ),
            'GetSectorList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSectorList,
                    request_deserializer=xtquant__pb2.Empty.FromString,
                    response_serializer=xtquant__pb2.GetSectorListResponse.SerializeToString,
            ),
            'DownloadHistoryData': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadHistoryData,
                    request_deserializer=xtquant__pb2.DownloadHistoryDataRequest.FromString,
                    response_serializer=xtquant__pb2.DownloadProgress.SerializeToString,
            ),
            'GetTradingDates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradingDates,
                    request_deserializer=xtquant__pb2.GetTradingDatesRequest.FromString,
                    response_serializer=xtquant__pb2.GetTradingDatesResponse.SerializeToString,
            ),
            'GetFinancialData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinancialData,
                    request_deserializer=xtquant__pb2.GetFinancialDataRequest.FromString,
                    response_serializer=xtquant__pb2.GetFinancialDataResponse.SerializeToString,
            ),
            'DownloadFinancialData': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFinancialData,
                    request_deserializer=xtquant__pb2.DownloadFinancialDataRequest.FromString,
                    response_serializer=xtquant__pb2.DownloadProgress.SerializeToString,
            ),
            'GetValuationMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValuationMetrics,
                    request_deserializer=xtquant__pb2.GetValuationMetricsRequest.FromString,
                    response_serializer=xtquant__pb2.GetValuationMetricsResponse.SerializeToString,
            ),
            'SubscribeQuote': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeQuote,
                    request_deserializer=xtquant__pb2.SubscribeQuoteRequest.FromString,
                    response_serializer=xtquant__pb2.QuoteUpdate.SerializeToString,
            ),
            'SubscribeWholeQuote': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeWholeQuote,
                    request_deserializer=xtquant__pb2.SubscribeWholeQuoteRequest.FromString,
                    response_serializer=xtquant__pb2.TickSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xtquant.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xtquant.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """====================== Service Definitions ======================

    Market data service — wraps xtquant.xtdata
    """

    @staticmethod
    def GetMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetMarketData',
            xtquant__pb2.GetMarketDataRequest.SerializeToString,
            xtquant__pb2.GetMarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFullTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetFullTick',
            xtquant__pb2.GetFullTickRequest.SerializeToString,
            xtquant__pb2.GetFullTickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstrumentDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetInstrumentDetail',
            xtquant__pb2.GetInstrumentDetailRequest.SerializeToString,
            xtquant__pb2.InstrumentDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetStockList',
            xtquant__pb2.GetStockListRequest.SerializeToString,
            xtquant__pb2.StockListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSectorList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetSectorList',
            xtquant__pb2.Empty.SerializeToString,
            xtquant__pb2.GetSectorListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadHistoryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.MarketDataService/DownloadHistoryData',
            xtquant__pb2.DownloadHistoryDataRequest.SerializeToString,
            xtquant__pb2.DownloadProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradingDates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetTradingDates',
            xtquant__pb2.GetTradingDatesRequest.SerializeToString,
            xtquant__pb2.GetTradingDatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFinancialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetFinancialData',
            xtquant__pb2.GetFinancialDataRequest.SerializeToString,
            xtquant__pb2.GetFinancialDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFinancialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.MarketDataService/DownloadFinancialData',
            xtquant__pb2.DownloadFinancialDataRequest.SerializeToString,
            xtquant__pb2.DownloadProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValuationMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.MarketDataService/GetValuationMetrics',
            xtquant__pb2.GetValuationMetricsRequest.SerializeToString,
            xtquant__pb2.GetValuationMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.MarketDataService/SubscribeQuote',
            xtquant__pb2.SubscribeQuoteRequest.SerializeToString,
            xtquant__pb2.QuoteUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeWholeQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.MarketDataService/SubscribeWholeQuote',
            xtquant__pb2.SubscribeWholeQuoteRequest.SerializeToString,
            xtquant__pb2.TickSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TradingServiceStub(object):
    """Trading service — wraps xtquant.xttrader
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderStock = channel.unary_unary(
                '/xtquant.TradingService/OrderStock',
                request_serializer=xtquant__pb2.OrderStockRequest.SerializeToString,
                response_deserializer=xtquant__pb2.OrderStockResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/xtquant.TradingService/CancelOrder',
                request_serializer=xtquant__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=xtquant__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.QueryAsset = channel.unary_unary(
                '/xtquant.TradingService/QueryAsset',
                request_serializer=xtquant__pb2.AccountRequest.SerializeToString,
                response_deserializer=xtquant__pb2.AssetInfo.FromString,
                _registered_method=True)
        self.QueryOrders = channel.unary_unary(
                '/xtquant.TradingService/QueryOrders',
                request_serializer=xtquant__pb2.QueryOrdersRequest.SerializeToString,
                response_deserializer=xtquant__pb2.QueryOrdersResponse.FromString,
                _registered_method=True)
        self.QueryTrades = channel.unary_unary(
                '/xtquant.TradingService/QueryTrades',
                request_serializer=xtquant__pb2.AccountRequest.SerializeToString,
                response_deserializer=xtquant__pb2.QueryTradesResponse.FromString,
                _registered_method=True)
        self.QueryPositions = channel.unary_unary(
                '/xtquant.TradingService/QueryPositions',
                request_serializer=xtquant__pb2.AccountRequest.SerializeToString,
                response_deserializer=xtquant__pb2.QueryPositionsResponse.FromString,
                _registered_method=True)
        self.SubscribeTrading = channel.unary_stream(
                '/xtquant.TradingService/SubscribeTrading',
                request_serializer=xtquant__pb2.AccountRequest.SerializeToString,
                response_deserializer=xtquant__pb2.TradingEvent.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """Trading service — wraps xtquant.xttrader
    """

    def OrderStock(self, request, context):
        """Place order -> xt_trader.order_stock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel order -> xt_trader.cancel_order_stock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAsset(self, request, context):
        """Query asset -> xt_trader.query_stock_asset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOrders(self, request, context):
        """Query orders -> xt_trader.query_stock_orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTrades(self, request, context):
        """Query trades -> xt_trader.query_stock_trades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPositions(self, request, context):
        """Query positions -> xt_trader.query_stock_positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTrading(self, request, context):
        """Subscribe to trading events (server stream) -> xt_trader.subscribe + callbacks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderStock': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderStock,
                    request_deserializer=xtquant__pb2.OrderStockRequest.FromString,
                    response_serializer=xtquant__pb2.OrderStockResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=xtquant__pb2.CancelOrderRequest.FromString,
                    response_serializer=xtquant__pb2.CancelOrderResponse.SerializeToString,
            ),
            'QueryAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAsset,
                    request_deserializer=xtquant__pb2.AccountRequest.FromString,
                    response_serializer=xtquant__pb2.AssetInfo.SerializeToString,
            ),
            'QueryOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOrders,
                    request_deserializer=xtquant__pb2.QueryOrdersRequest.FromString,
                    response_serializer=xtquant__pb2.QueryOrdersResponse.SerializeToString,
            ),
            'QueryTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTrades,
                    request_deserializer=xtquant__pb2.AccountRequest.FromString,
                    response_serializer=xtquant__pb2.QueryTradesResponse.SerializeToString,
            ),
            'QueryPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPositions,
                    request_deserializer=xtquant__pb2.AccountRequest.FromString,
                    response_serializer=xtquant__pb2.QueryPositionsResponse.SerializeToString,
            ),
            'SubscribeTrading': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTrading,
                    request_deserializer=xtquant__pb2.AccountRequest.FromString,
                    response_serializer=xtquant__pb2.TradingEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xtquant.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xtquant.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """Trading service — wraps xtquant.xttrader
    """

    @staticmethod
    def OrderStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/OrderStock',
            xtquant__pb2.OrderStockRequest.SerializeToString,
            xtquant__pb2.OrderStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/CancelOrder',
            xtquant__pb2.CancelOrderRequest.SerializeToString,
            xtquant__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/QueryAsset',
            xtquant__pb2.AccountRequest.SerializeToString,
            xtquant__pb2.AssetInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/QueryOrders',
            xtquant__pb2.QueryOrdersRequest.SerializeToString,
            xtquant__pb2.QueryOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/QueryTrades',
            xtquant__pb2.AccountRequest.SerializeToString,
            xtquant__pb2.QueryTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xtquant.TradingService/QueryPositions',
            xtquant__pb2.AccountRequest.SerializeToString,
            xtquant__pb2.QueryPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xtquant.TradingService/SubscribeTrading',
            xtquant__pb2.AccountRequest.SerializeToString,
            xtquant__pb2.TradingEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
